package main

// DO NOT EDIT
// Generated by: ./tools/gen_sprite_tags.sh

type playerAnimationTags uint8

const (
	playerIdle playerAnimationTags = iota
	playerClimpingupdown
	playerClimbingleftright
	playerClimbingdiagonally
	playerJumpingstart
	playerJumpingmidair
	playerJumpingend
	playerSlippingstart
	playerSlippingscrambling
	playerSlippingrecovery
	playerFallingstart
	playerFallingfreefall
	playerFallingrecovery
)

var playerAnimationNames = []string{
	"Idle",
	"Climping up/down",
	"Climbing left/right",
	"Climbing diagonally",
	"Jumping start",
	"Jumping midair",
	"Jumping end",
	"Slipping start",
	"Slipping scrambling",
	"Slipping recovery",
	"Falling start",
	"Falling freefall",
	"Falling recovery",
}
