name: Build Executables
on: [push]
jobs:

  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.23
    - name: Install dependencies
      shell: bash
      run: sudo apt-get update && sudo apt-get -y install libgl1-mesa-dev xorg-dev libasound2-dev
    - name: Run tests
      shell: bash
      run: xvfb-run go test -v ./...

  build-win:
    name: Build Windows binary
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.23
    - name: Install dependencies
      shell: bash
      run: go install github.com/akavel/rsrc@latest
    - name: Generate icon resource
      shell: bash
      run: rsrc -ico artwork/icon.ico
    - name: Build Windows exe
      shell: bash
      run: go build -v -tags release .
    - name: Build Windows testing exe
      shell: bash
      run: go build -v -o project-scale-testing.exe .
    - name: Build Windows collision debug exe
      shell: bash
      run: go build -v -tags debugcol -o project-scale-debugcol.exe .
    - name: Upload Windows exe
      uses: actions/upload-artifact@v3
      with:
        name: project-scale-win
        path: |
          LICENSE
          project-scale.exe
          project-scale-testing.exe
          project-scale-debugcol.exe

  build-mac:
    name: Build MacOS binary
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.23
    - name: Build Mac exe
      shell: bash
      run: go build -v -tags release .
    - name: Tar it up
      shell: bash
      run: tar -zcvf project-scale-mac.tar.gz project-scale LICENSE
    - name: Upload Mac exe
      uses: actions/upload-artifact@v3
      with:
        name: project-scale-mac
        path: project-scale-mac.tar.gz

  build-lin:
    name: Build Linux binary
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.23
    - name: Install dependencies
      shell: bash
      run: sudo apt-get update && sudo apt-get -y install libgl1-mesa-dev xorg-dev libasound2-dev
    - name: Build Linux exe
      shell: bash
      run: go build -v -tags release .
    - name: Tar it up
      shell: bash
      run: tar -zcvf project-scale-lin.tar.gz project-scale LICENSE
    - name: Upload Linux exe
      uses: actions/upload-artifact@v3
      with:
        name: project-scale-lin
        path: project-scale-lin.tar.gz

  build-web:
    name: Build Web binary
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.23
    - name: Build Web binary
      shell: bash
      run: GOOS=js GOARCH=wasm go build -v -ldflags "-w -s" -o dist/web/project-scale.wasm -tags release .
    - name: Copy WASM exec script
      shell: bash
      run: cp $(go env GOROOT)/misc/wasm/wasm_exec.js dist/web/.
    - name: Upload Web build
      uses: actions/upload-artifact@v3
      with:
        name: project-scale-web
        path: |
          dist/web/
          LICENSE

  upload-bundle:
    name: Bundle binaries with dev assets
    runs-on: ubuntu-latest
    needs: [tests, build-lin, build-mac, build-win]
    steps:
    - uses: actions/checkout@v3
    - name: Download Windows binary
      uses: actions/download-artifact@v3
      with:
        name: project-scale-win
    - name: Download Linux binary
      uses: actions/download-artifact@v3
      with:
        name: project-scale-lin
    - name: Download Mac binary
      uses: actions/download-artifact@v3
      with:
        name: project-scale-mac
    - name: Upload beta testing bundle
      uses: actions/upload-artifact@v3
      with:
        name: project-scale-bundle
        path: |
          README.md
          LICENSE
          project-scale-lin.tar.gz
          project-scale-mac.tar.gz
          project-scale.exe
          project-scale-testing.exe
          project-scale-debugcol.exe

  deploy-win:
    name: Deploy Windows build to itch.io
    if: startsWith(github.event.ref, 'refs/tags/v')
    needs:
      - build-win
      - tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: project-scale-win
    - uses: josephbmanley/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: windows
        ITCH_GAME: project-scale
        ITCH_USER: sinisterstuf
        PACKAGE: project-scale.exe
        VERSION: ${{github.ref_name}}

  deploy-mac:
    name: Deploy MacOs build to itch.io
    if: startsWith(github.event.ref, 'refs/tags/v')
    needs:
      - build-mac
      - tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: project-scale-mac
    - name: Extract tarball
      shell: bash
      run: tar -zxvf project-scale-mac.tar.gz
    - uses: josephbmanley/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: mac
        ITCH_GAME: project-scale
        ITCH_USER: sinisterstuf
        PACKAGE: project-scale
        VERSION: ${{github.ref_name}}

  deploy-lin:
    name: Deploy Linux build to itch.io
    if: startsWith(github.event.ref, 'refs/tags/v')
    needs:
      - build-lin
      - tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: project-scale-lin
    - name: Extract tarball
      shell: bash
      run: tar -zxvf project-scale-lin.tar.gz
    - uses: josephbmanley/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: linux
        ITCH_GAME: project-scale
        ITCH_USER: sinisterstuf
        PACKAGE: project-scale
        VERSION: ${{github.ref_name}}

  deploy-web:
    name: Deploy Web build to itch.io
    if: startsWith(github.event.ref, 'refs/tags/v')
    needs:
      - build-web
      - tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: project-scale-web
    - uses: josephbmanley/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: web
        ITCH_GAME: project-scale
        ITCH_USER: sinisterstuf
        PACKAGE: dist/web
        VERSION: ${{github.ref_name}}
